### ISSUE TITLE
Exception zcx_mdp_json_invalid occured, but JSON validators found input as valid

### ISSUE THREAD

**Issue by attilaberencsi** [fatihpense/zcl_mdp_json#1]
Hello Faith,

first of all thank you sharing this great tool. I run into trouble when parsing a JSON string in ABAP. I turned on the debug feature by the constant available in your class to find the place, before the exception occurs. I spent some time, but finally decided rather to hand over this investigation to the master, because I'm not yet so familiar with your tool in detail. It would be great, if you can check this issue. I've created a test report for you, to analyze it, where you can tick option Display Before Parsing to show a dialog with the formatted version of the JSON, before the deserialization is called.
[json.txt](https://github.com/fatihpense/zcl_mdp_json/files/361819/json.txt)
[json_parser.txt](https://github.com/fatihpense/zcl_mdp_json/files/361820/json_parser.txt)
Thank you
Attila

**Comment by fatihpense** [comment]
Hello Atilla, 
I just saw this issue. I will look at it ASAP. 
Thank you for feedback!
Fatih

**Comment by fatihpense** [comment]
Hi Attila, I have examined your excellent bug report. It seems that I embarrassingly forgot true, false and null values in deserializer! There was support for these values in the node class, so you only need to update your deserializer class: "zcl_mdp_json_deserializer"

I have added a few lines to your code for usage example. 
Example for getting value:

``` ABAP
  DATA: has_deletions TYPE string.
  has_deletions = root_node->object_get_child_node( key = 'status'
    )->object_get_child_node( key = 'otifioridoc'
    )->object_get_child_node( key = 'index'
    )->object_get_child_node( key = 'hasDeletions')->value.

  WRITE: 'status->otifioridoc->index->hasDeletions : ' , has_deletions.
```

Example for comparing true/false with json_type as an alternative to string value comparison:

``` ABAP
  DATA: current_node TYPE REF TO zcl_mdp_json_node.
  current_node = root_node->object_get_child_node( key = 'status'
      )->object_get_child_node( key = 'otifioridoc'
      )->object_get_child_node( key = 'index'
      )->object_get_child_node( key = 'current').
  IF current_node->json_type = zcl_mdp_json_node=>co_json_true.
    WRITE: / 'current value is true.'.
  ELSE.
    WRITE: / 'current value is false.'.
  ENDIF.
```

Here is the file:
[json_parser_with_examples.txt](https://github.com/fatihpense/zcl_mdp_json/files/372524/json_parser_with_examples.txt)

Thank you for your bug report and interest.
Best wishes,
Fatih.

**Comment by attilaberencsi** [comment]
Hi Faith,

Everything is fine now with your correction. Thank you very much for your help and support. This tool is really great and convenient to use.
(I've just come back from vacation sorry for my answer delay. )
Best regards
Attila
