### ISSUE TITLE
problem in the example for pull request fix for SAP 7.30

### ISSUE THREAD

**Issue by rzablah** [fatihpense/zcl_mdp_json#13]
Hello there...
in the report ZEXAMPLE_ZCL_MDP_JSON_DESERIALIZE_1 (part of the example for deserialize) when i implement the pull request fix for SAP 7.30 I have an sintaxis error when i try to activate the program in the line:

"l_string = l_json_root_object->object_get_child_node( key = 'books' )->array_get_child_node( index = 1 )->object_get_child_node( key = 'quote_english' )->value."

Unable to interpret "INDEX". Possible causes: Incorrect spelling or comma error. the same thing appenning with the key on that sentence...

i know the sentenced is malformed for 7.30
any ideas? 
thanks in advance
kind regards,
Rafael Zablah

**Comment by egemenyilmaz** [comment]
Hello @rzablah 

You may need to use "_CALL METHOD_" instead of inline call like _object->method( param = val )_ syntax.

Example:

CALL METHOD l_json_root_object-> object_get_child_node
  EXPORTING
    key = 'books'
  RECEIVING
    node = lo_node
    
and continue with other calls in the chain.

**Comment by rzablah** [comment]
Hello egemenyilmaz, thank you for your answer, it work perfect.
kind regards,
