### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by attilaberencsi** [fatihpense/zcl_mdp_json#5]
Hi,

I tried to deserialize the following string wiith zcl_mdp_json_deserializer, but it failed, could you please check: (it was valid on https://jsonlint.com/):
{"tileConfiguration":"{\"display_icon_url\":\"sap-icon://home-share\",\"display_number_unit\":\"\",\"service_url\":\"/sap/opu/odata/sap/ZPA_STATUTORY_SRV/TripDetailsSet/$count?$filter=TravelType eq '9'\",\"service_refresh_interval\":0,\"navigation_use_semantic_object\":true,\"navigation_target_url\":\"#Employee-ManageMyStatutoryTravel\",\"navigation_semantic_object\":\"Employee\",\"navigation_semantic_action\":\"ManageMyStatutoryTravel\",\"navigation_semantic_parameters\":\"\",\"display_search_keywords\":\"ESS statutory travel\"}"}

Thank you
Attila

**Comment by fatihpense** [comment]
Hi Attila,
I hope you are fine :)

It seems these quotes are extra, can you check it is copied correctly?

```
{"tileConfiguration":
" <---------------
{"display_icon_url":"sap-icon://home-share",
"display_number_unit":"",
"service_url":"/sap/opu/odata/sap/ZPA_STATUTORY_SRV/TripDetailsSet/$count?$filter=TravelType eq '9'",
"service_refresh_interval":0,
"navigation_use_semantic_object":true,
"navigation_target_url":"#Employee-ManageMyStatutoryTravel",
"navigation_semantic_object":"Employee",
"navigation_semantic_action":"ManageMyStatutoryTravel",
"navigation_semantic_parameters":"",
"display_search_keywords":"ESS statutory travel"}
" <---------------
}
```

Edit: I deleted the extra quotes this should work fine:

```
{"tileConfiguration":
	{"display_icon_url":"sap-icon://home-share",
	"display_number_unit":"",
	"service_url":"/sap/opu/odata/sap/ZPA_STATUTORY_SRV/TripDetailsSet/$count?$filter=TravelType eq '9'",
	"service_refresh_interval":0,
	"navigation_use_semantic_object":true,
	"navigation_target_url":"#Employee-ManageMyStatutoryTravel",
	"navigation_semantic_object":"Employee",
	"navigation_semantic_action":"ManageMyStatutoryTravel",
	"navigation_semantic_parameters":"",
	"display_search_keywords":"ESS statutory travel"}
}
```


regards,
Fatih

**Comment by attilaberencsi** [comment]
Thank You Faith,
it seemed a temporary issue which I could not reproduce a week after, when I come back to this code.
I close the Issue, and thank You very much again for Your Great Solution!
